# General
exclude: [README.md, scripts]
url: "https://thewarpaint.github.io/caracteres"

# i18n
languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["assets"]
parallel_localization: true
