# General
exclude: [README.md, scripts]
url: "https://caracteres.io"

plugins:
  - jekyll-polyglot

# i18n
languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["assets"]
parallel_localization: true
