version: 2
jobs:
  build:
    working_directory: ~/caracteres

    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "33:08:48:52:50:74:4c:c7:9e:f2:33:d6:c5:01:6c:91"

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            bundle install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Build static website
          command: |
            ./scripts/build.sh

      - run:
          name: Run HTMLProofer tests
          command: |
            bundle exec htmlproofer ./_site --check-html --disable-external

      - run:
          name: Configure git user info
          command: |
            git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
            git config --global user.name "$GH_NAME" > /dev/null 2>&1

      - deploy:
          name: Publish static website
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/publish.sh
            fi
