version: 2
jobs:
    build:
      branches:
        only:
          - master

      working_directory: ~/caracteres

      docker:
        - image: jbergknoff/sass:latest

      steps:
          - checkout

          - add_ssh_keys:
              fingerprints:
                - "33:08:48:52:50:74:4c:c7:9e:f2:33:d6:c5:01:6c:91"

          - run:
              name: Build static website
              command: |
                ./scripts/build.sh

          - run:
              name: Configure git user info
              command: |
                  git config --global user.email "eduardogarcia.xyz+gh@gmail.com"
                  git config --global user.name "Eduardo Garcia"

          - run:
              name: Publish static website
              command: |
                  ./scripts/publish.sh
